### ISSUE TITLE
Crest Logo 

### ISSUE THREAD

**Issue by carsoa** [govau/dta-gov-au#135]
Crest logo need to be crisper/sharper. Align to the left margin

**Comment by imperator99** [comment]
@carsoa the current crest is a double sized PNG to accomodate retina screens. In order to make it sharper you will need to supply an SVG.

**Comment by imperator99** [comment]
This will be fixed using an SVG file with a PNG fallback according to this: https://css-tricks.com/a-complete-guide-to-svg-fallbacks/.

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-gov-au/pull/152.
