### ISSUE TITLE
Tab outline/set focus

### ISSUE THREAD

**Issue by carsoa** [govau/dta-gov-au#140]
set focus state colours to UiKit defaults

**Comment by imperator99** [comment]
Are you sure? (This has changed since I implemented the colours).
![screen shot 2018-04-12 at 8 41 45 am](https://user-images.githubusercontent.com/4567284/38646948-5f98be62-3e2d-11e8-821c-d26ecc1bb830.png)

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-gov-au/pull/149.
