### ISSUE TITLE
spacing of components in home header - revert to Design System default spacing

### ISSUE THREAD

**Issue by adrian-yee** [govau/dta-gov-au#163]

**Comment by adrian-yee** [comment]
remove any overides or additional space requested previously and revert to Design System component values for font height, line height, margin, weight etc

**Comment by imperator99** [comment]
This is done; however there were instructions from @carsoa regarding spacing of the heading within the header. May need revisiting. Otherwise resolved by https://github.com/govau/dta-gov-au/pull/223.
