### ISSUE TITLE
Entering a new author's position title [author name] is the [position]

### ISSUE THREAD

**Issue by nicolakcoady** [govau/dta-gov-au#17]
Might need some re-thinking for when someone isn't the only person at the DTA with that title.

For example:
Marika is the enterprise architect working with the Chief Technology Officer Group at the DTA.

Should be: 
Marika is an enterprise architect working with the Chief Technology Officer Group at the DTA.

**Comment by imperator99** [comment]
I think a good resolution to this might be to just use the entire line in the appropriate field. For example in the 'Position' field, the entire text might be, 'Marika is an enterprise architect working with the Chief Technology Officer Group at the DTA'.

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-website-rebuild/pull/68.
