### ISSUE TITLE
Add sign-up redirect

### ISSUE THREAD

**Issue by imperator99** [govau/dta-gov-au#176]
With the removal of the top-level left-hand menu items, blogs and news pages will no longer have menus. Instead, they can have a redirect to the sign up form on the old site. FOR FREE!

**Comment by adrian-yee** [comment]
![sign-up](https://user-images.githubusercontent.com/22947795/38963359-dbe835d8-43b4-11e8-96de-600e26f3e133.png)
here is the visual design for the sign up element - please change the icon to the 'action ' colour

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-gov-au/pull/201 and https://github.com/govau/dta-website-rebuild/pull/289.
