### ISSUE TITLE
Card list match hight doesnt work in IE

### ISSUE THREAD

**Issue by iijiang** [govau/dta-gov-au#244]
it works in Chrome, but not in IE 10, e.g. https://beta.dta.gov.au/our-projects

**Comment by imperator99** [comment]
Hi @iijiang thanks for letting me know. Can you please post a screenshot along with your browser details?
Thanks, Jesse.

**Comment by iijiang** [comment]
Its windows 10 ie 11. 
![beta-dta-sh-2](https://user-images.githubusercontent.com/512584/39417086-4dac39ba-4c95-11e8-8ed4-01dc1a41ea38.png)
![beta-dta-sh-1](https://user-images.githubusercontent.com/512584/39417091-54184f00-4c95-11e8-8521-cf56dec7ecf9.png)

**Comment by iijiang** [comment]
You also could test it on crossbrowsertesting.com, it has free trail.

**Comment by imperator99** [comment]
Hi @iijiang can you please test again? I believe this has been resolved.

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-gov-au/pull/311.

**Comment by iijiang** [comment]
yep, I saw it on the other day. Nice work.
