### ISSUE TITLE
Should the content be full width if there is no left or right nav?

### ISSUE THREAD

**Issue by iijiang** [govau/dta-gov-au#245]
looking at contact_us page(https://beta.dta.gov.au/contact-us), should the content be centre?

**Comment by imperator99** [comment]
Hi @iijiang, I'm not getting this behaviour. Can you please send through a screenshot along with your browser details?
Thanks, Jesse.

**Comment by iijiang** [comment]
![screen shot 2018-04-30 at 4 45 09 pm copy](https://user-images.githubusercontent.com/512584/39417440-88531e60-4c97-11e8-9c94-28c30728c26e.png)
I am not sure we are at same boat, I have to re-look beta.dta site for this. You could close it if you think its not a issue for you. (please also look: https://www.drupal.org/project/drupal/issues/953034)

**Comment by iijiang** [comment]
the problem on contact page might be different, thinking why you have "max-width: 42em" on "p" tag. Should the sentence be full width?
![screen shot 2018-04-30 at 5 06 12 pm](https://user-images.githubusercontent.com/512584/39417630-00f919c2-4c99-11e8-9f24-4ce198babdc7.png)

**Comment by imperator99** [comment]
Oh right, thanks for pointing that out. Resolved by https://github.com/govau/dta-website-rebuild/pull/334.
As for the max-width on p tags, we do that for readability, as explained [here](https://baymard.com/blog/line-length-readability) (and elsewhere).
