### ISSUE TITLE
Global change – typographic scale and spacing

### ISSUE THREAD

**Issue by carsoa** [govau/dta-gov-au#256]
- **H1 and H2** = margin-top = 3rem; **H2** when following straight after **H1** margin-top = 1.5rem; **H3-H6** and P margin-top = 1.5rem; **list items** margin-top 0.5rem

- H1 p change line height to 1.3

- H2 p change line height to 1.25

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-gov-au/pull/323.
