### ISSUE TITLE
No little pics appearing on old blogs

### ISSUE THREAD

**Issue by nicolakcoady** [govau/dta-gov-au#363]
Went into the author information and the DTA logo should be appearing but it isn't. 

See screenshot
![screen shot 2018-07-25 at 10 05 16 am](https://user-images.githubusercontent.com/36524570/43172374-5c81c23e-8ff2-11e8-9385-2fc12b111444.png)

**Comment by imperator99** [comment]
Thanks @nicolakcoady. We're planning to remove author images and names from cards to simplify them to reflect our user research. I'm marking this as 'won't fix', but it is interesting behaviour regarding default images.
