### ISSUE TITLE
Print CSS

### ISSUE THREAD

**Issue by carsoa** [govau/dta-gov-au#367]
Could you please look into the print CSS for the website (Corporate plan is coming up in 3 weeks)

**Comment by imperator99** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create print css.](https://trello.com/c/rzm5IovK/416-create-print-css)

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-gov-au/pull/378.
