### ISSUE TITLE
Images to the edge (examples in Guides).

### ISSUE THREAD

**Issue by MattFredBrooks** [govau/dta-gov-au#4]
Guides has examples of this pattern.

Two types of example in Guides (one for decorative images that get cropped and one for images with not cropping).
Examples here: https://ausdta.slack.com/archives/C7L13C7SR/p1518390371000088

Discussion in Slack with helpful comments from Alex Baranov who knows Guides really well.
https://ausdta.slack.com/archives/C7L13C7SR/p1518390371000088

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-gov-au/commit/4307b66fd1e73e4a60bea825a5bdfebd28194b53.
