### ISSUE TITLE
Blog publishing date

### ISSUE THREAD

**Issue by nicolakcoady** [govau/dta-gov-au#407]
If blogs are published on same day, they get ordered alphabetically rather than by the time they are posted.

**Comment by imperator99** [comment]
One possible solution might be to add a new field to the blog and news items content types to hold full date and times. All new items could the be sorted by this more granular field, while older items could be sorted by the less granular field. We would need to be sure that items could first be sorted on the existence of data in the new and old fields, as old items wouldn't have the new field, and vice versa.
