### ISSUE TITLE
Author info and tags are indented

### ISSUE THREAD

**Issue by nicolakcoady** [govau/dta-gov-au#409]
Is it meant to be like this?

![screen shot 2018-11-13 at 3 31 29 pm](https://user-images.githubusercontent.com/36524570/48391124-4a552600-e759-11e8-9bef-effa0679b879.png)

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-gov-au/compare/Issue-409---Author-info-and-tags-are-indented?expand=1.
