### ISSUE TITLE
Ribbon at top of header in site using accordion.

### ISSUE THREAD

**Issue by MattFredBrooks** [govau/dta-gov-au#5]
Here are some resources for the ribbon from Trevro Brennan. Ask Alex Page if more assistance is required as they used a different tech stack than we probably are. Note: requires accordion.

https://github.com/govau/GOLD/blob/develop/src/layout/structure/header-govau.js

https://github.com/govau/GOLD/blob/develop/src/sass/components/_header-govau.scss (edited)
Note: requires accordion.

Note: Guides is also using the ribbon as an example.

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-gov-au/pull/117
