### ISSUE TITLE
Solution to possible blog card author name is too long.

### ISSUE THREAD

**Issue by MattFredBrooks** [govau/dta-gov-au#56]
Up to you. 
Maybe wrap text to line below so it doesn't run into to author image.
![screen shot 2018-03-08 at 11 02 03 am](https://user-images.githubusercontent.com/10394129/37125464-dd7a6016-22c0-11e8-927f-7c32fe167b16.png)

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-gov-au/pull/74.

This solution repositions the author images so they won't overlap. The new position also has the benefit of covering up existing wordmarks on some images, so authors won't have to upload new versions.
