### ISSUE TITLE
Style table with border bottom row lines

### ISSUE THREAD

**Issue by MattFredBrooks** [govau/dta-gov-au#62]
Remove background row colors for table row except for column header row. Add border bottom 1px light grey e.g. #f5f5f5 to table rows.
![simpletablelines](https://user-images.githubusercontent.com/10394129/37131059-be8952ba-22da-11e8-80bf-10e1cfc4f55c.png)

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-gov-au/pull/77.
