### ISSUE TITLE
Provide uniform indentation for all side navigation menu items

### ISSUE THREAD

**Issue by MattFredBrooks** [govau/dta-gov-au#88]
Make sure the indentation for all items (whether they are selected or not) have a uniform indentation per level of the hierarchy, so that there is no visual confusion as to which level each item is on and they are all matching to each others siblings and differ between parents and children.

**Comment by imperator99** [comment]
@MattFredBrooks do you have an example where this isn't happening in the way you expect?

**Comment by imperator99** [comment]
Resolved by https://github.com/govau/dta-gov-au/pull/103.
